manifest:
remotes:
    - name: sayu-hub
      url-base: https://github.com/sayu-hub
  projects:
    - name: zmk-pmw3610-driver
      remote: sayu-hub
      revision: main  # または具体的なコミットハッシュ
      path: modules/zmk-pmw3610-driver
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

  self:
    path: config
